### ISSUE TITLE
ACTION: unbound variable

### ISSUE THREAD

**Issue by dalealleshouse** [mbovo/action-helm-artifactory#3]
yaml:

``` yaml
 name: "Helm checks"
        uses: mbovo/action-helm-artifactory@v1.0.0
        with:
          action: "check"
        env:
          ARTIFACTORY_URL: <>
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
```

Running the build results in this error:

`home/runner/work/_actions/mbovo/action-helm-artifactory/v1.0.0/main.sh: line 15: ACTION: unbound variable`
